spring:
    datasource:
        username: root
        password: root

        # MySQL version JAR dependencies need modify together
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://172.20.160.120:13308/sharding_db # MySQL

        # postgresql version JAR dependencies need modify together
#        driver-class-name: org.postgresql.Driver
#        url: jdbc:postgresql://172.20.160.120:13308/sharding_db

server:
    port: 8081


mybatis:
    mapperLocations: classpath:mapper/*.xml
